version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x


  pre_build: 
    commands:
    - chmod +x *.sh

    # terraform installation
    - ./banana.sh

    #configure profile
    - ./orange.sh

  build:
    commands:
    - ./apple.sh